### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Wanjie-Feng** [Adamtaranto/TRF2GFF#2]
hi,
Why does the requirements.txt file have no content? I got an error when I used the following code:
```
pip install -e .
```
```
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
```

**Comment by Adamtaranto** [comment]
The `requirements.txt` file is just part of the template and it should not make a difference to the build. 

Which `python --version` are you using?

**Comment by Wanjie-Feng** [comment]
Python 3.7.16

**Comment by Adamtaranto** [comment]
I've tested trf2gff with Python=3.8 (minimum version supported by conda) and it works.

Try one of the following:
- Create a env with a newer version of python i.e. 
```bash
# Create a clean env with the latest version of python
conda create -n trf2gff-env python=3.12
# Activate the new env
conda activate trf2gff-env
# Install trf2gff
pip install git+https://github.com/Adamtaranto/TRF2GFF.git
```
- Upgrade your local Python to a version >= 3.8

Edit: This seems to be due the build dependency [setuptools-scm](https://github.com/pypa/setuptools_scm) requiring Python >= 3.8
